
test_control_fun: test_control_fun.cpp ../control_fun.h ../control_fun.cpp
	g++ test_control_fun.cpp ../control_fun.cpp -lm -o test_control_fun

test_logger: test_logger.cpp ../logger.h
	g++ test_logger.cpp -o test_logger