# Copyright 2024 Figure AI, Inc
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "obot-parser",
    srcs = [
        "obot-parser.cpp",
    ],
    hdrs = [
        "obot-parser.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//firmware/lib/crc",
    ],
)
